import type { GlobalThemeOverrides } from 'naive-ui'

export const themeOverrides: GlobalThemeOverrides = {
  common: {
    primaryColor: '#4f46e5',
    primaryColorHover: '#4338ca',
    primaryColorPressed: '#3730a3',
    primaryColorSuppl: '#6366f1',
    borderRadius: '8px',
    borderRadiusSmall: '6px',
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    fontSize: '0.875rem',
    fontSizeMedium: '14px',
    fontSizeSmall: '13px',
    fontSizeTiny: '12px',
    textColorBase: '#0f172a',
    textColor1: '#0f172a',
    textColor2: '#334155',
    textColor3: '#64748b',
    borderColor: '#e2e8f0',
    dividerColor: '#e2e8f0',
    inputColor: '#f8fafc',
    cardColor: '#ffffff',
    bodyColor: '#f1f5f9',
    hoverColor: '#f1f5f9',
    heightSmall: '30px',
    heightMedium: '34px',
  },
  Card: {
    borderRadius: '12px',
    borderColor: '#e2e8f0',
    paddingSmall: '12px 16px',
    titleFontSizeSmall: '14px',
    titleFontWeight: '600',
  },
  Button: {
    borderRadiusMedium: '8px',
    borderRadiusSmall: '6px',
    borderRadiusTiny: '5px',
    fontWeightStrong: '500',
  },
  Input: {
    borderRadius: '8px',
    heightSmall: '30px',
    heightMedium: '34px',
  },
  Tag: {
    borderRadius: '6px',
    fontSizeSmall: '11px',
    fontSizeTiny: '10px',
  },
  Tabs: {
    tabFontSizeSmall: '13px',
    tabFontWeightActive: '600',
    tabGapSmallLine: '20px',
  },
  Empty: {
    textColor: '#94a3b8',
    iconColor: '#cbd5e1',
    fontSizeSmall: '13px',
  },
}
